[project]
name = "samsbet"
version = "2.0.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# <<< ADIÇÃO AQUI >>>
# Diga explicitamente ao setuptools qual pasta é o nosso pacote
[tool.setuptools]
packages = ["samsbet"]